[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "bcdcf4bbadc8de23b64666c5c8c3b52548f8d843"
os = "macos"

    [[Libffi.download]]
    sha256 = "ef29526d33decb7e04675de2b38c0b365d0ceea055e792cbeeaf3e91d0045581"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.aarch64-apple-darwin.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "aa29647979c5f0164a7026736c762c9571444d2c"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "2de51d7a15b1d7a71adc062a25a9ee01ba508f0b717e64392e2f2ffb0a40be5f"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.aarch64-linux-gnu.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "7abf2fb99a831c84700be0cac5d2ab71be50e2ee"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "b248c995cd3d6fcd2321eb953b04e531cf20e64d05a42e01334073a179551026"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.aarch64-linux-musl.tar.gz"
[[Libffi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b31ddde9e2c2213789348aea4509bd16ea6e42a4"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "2f4e49b9a33cc4d3929167ce9e232d8f7c3f3390831fc3605a5ef28c62ecc0fe"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.armv6l-linux-gnueabihf.tar.gz"
[[Libffi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0f67a0063779033fff2b22f4138deb56ef3a0b8"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "f7d14719befb3b8da98d851080082adc1349c0e2412b423011640ac48f775a1f"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.armv6l-linux-musleabihf.tar.gz"
[[Libffi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6b67b43f7ea7b36825eeaa5925916dfc1e197f5"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "c577b2b29a66bdb155907bbdd78fdb95cf3ddfa0228cc8bf2f94f3062a8f2810"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.armv7l-linux-gnueabihf.tar.gz"
[[Libffi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d02e0f97e266ff259fca36585527293dcf3013c"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "5989d7835e68ed817f51a82ecc9c67331fa834fbdc15c9b0f39e5d5022430311"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.armv7l-linux-musleabihf.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "3b340eed6889167361e9c2da1d798f0784cc709a"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "bf0e2b3dc6c8bd672a2b341bd8c69c28eca812dd5a63b824e525d690f1d0e168"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.i686-linux-gnu.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "157bcc207c2f5af7c12ce9955aa3a888d284c789"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "f649275d0643b2007cd373d0675802f3e5a64f7f79417896153c084f3d08e6a3"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.i686-linux-musl.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "8c9ab2590c824644f7f6c593321444cc2a98d897"
os = "windows"

    [[Libffi.download]]
    sha256 = "53e9fbae33dc4df875e8363b7e3b24f1afdf7149bab472c880886f9e62e51cb3"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.i686-w64-mingw32.tar.gz"
[[Libffi]]
arch = "powerpc64le"
git-tree-sha1 = "c77f7e05ad1268fa60e003d042a9e1d869d616ee"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "8dcdcb560aa3d46b336822a2cf05a479051c74b96c94027756a51e75b4ac60ff"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.powerpc64le-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "b19102c110b6df1388e63185f64eb395df8c50ef"
os = "macos"

    [[Libffi.download]]
    sha256 = "2692b359b1c7d56cd22ae8c527a6cf9de349194aa9d196c95e41c5f2ede2ab5e"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.x86_64-apple-darwin.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "c9aaded566f11747c78615cd5ae9fc27528129de"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "e74d1976ab7f0f8b834e6517942a4c0d51194d85506e12eb1f0dfbc9ab1dcfe9"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.x86_64-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "607a25448d2a44642834a3ce834233619a3fe7f8"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "586686cce60484cb0220b380cdbfedc3e86b5bf900a65dd4dcc128445f5d3153"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.x86_64-linux-musl.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "437cad6a516ea6124f9ef25c58418961bc24d34a"
os = "freebsd"

    [[Libffi.download]]
    sha256 = "0d0bcc6393c867cbf1f95c5e9676b68b4d91c5b62a248322ec66643d6f97fa11"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.x86_64-unknown-freebsd.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "02cc19c960f53e8888cbdb9bb7fbccd15a60da7c"
os = "windows"

    [[Libffi.download]]
    sha256 = "030f9d18ffe544fba7a41ca5ea33ab49eaefd19222a8960809b7acc742e439d8"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.4.4+0/Libffi.v3.4.4.x86_64-w64-mingw32.tar.gz"
