[[Libffi]]
arch = "i686"
git-tree-sha1 = "fe0c66aff73d0c7a38f6de8342d6310e904a8089"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "8663e24be61b98727e18a12bfc4e87169f2cb0f76492129e23bf4592a2ea414b"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.i686-linux-musl.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "cad92ff0c3aa3db661be468d66526a2e3d97875a"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "90d0ef92f633c8779652406669c96497b8221663ef4dd6689a57645687d04ffc"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.aarch64-linux-musl.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "f3e7c0d80df2c97a0175fa8ba66f4f8a1d2f1a72"
os = "windows"

    [[Libffi.download]]
    sha256 = "09544d8675675c196a6eb4e1531024fcee9e64c2e75b46c67ef4b142eb36e7d9"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.i686-w64-mingw32.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "3ab4eb4c812ffa85aa74e86d170367d3690b7433"
os = "windows"

    [[Libffi.download]]
    sha256 = "32e6dbe66d2535beaecbb0e4e174389f539b86b6978b444b74f324312d702eee"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.x86_64-w64-mingw32.tar.gz"
[[Libffi]]
arch = "armv7l"
git-tree-sha1 = "db6a8d0274682381bd1c8d1856b1ca4f0af7f2ac"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "1d45b92c9a1e2191bf53dd1c665b638200461cd390f8fab272e64a753806f689"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.armv7l-linux-gnueabihf.tar.gz"
[[Libffi]]
arch = "armv7l"
git-tree-sha1 = "e596419619393cf07ba1d434fdaa2f2b01b26939"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "5b86345012606f983ff2c387ed1f106d6e1609135d78612f197942bbc623fb48"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.armv7l-linux-musleabihf.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "0546f77973fdd72818272b3c23039dc70f1fe1a0"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "36c4eb34a8f98f1daba08452fc028d7b07d14bbd19e365ac7d9362cf4258e9d9"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.i686-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "66f1c96dbb441e335a6658779ea5106f76739677"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "56758d8d2b5f61ae6d5ef182ae0424f25a284a4647ba365d34ab22347427ec7c"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.x86_64-linux-gnu.tar.gz"
[[Libffi]]
arch = "powerpc64le"
git-tree-sha1 = "2ad085ad7a5e2044b5ba60bf5b0ae7f8f2de5555"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "152c2456744a0f2d002ac78dd8a4fdf1a75679d1edcfd5a444278488c597c1bd"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.powerpc64le-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "f9799a42a187b41bea99fd1fe5e7c1f73705c1bd"
os = "macos"

    [[Libffi.download]]
    sha256 = "a4a2a759bd4ad920a51413b0f28da1dc170c10b7127789acec29d16e9bd9b357"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.x86_64-apple-darwin14.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "6a8ead3f936f11feb99d8775d5e14e93640f46bd"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "5a81de8433b487a9910ba662130dc2374be65049b68952d23f5e144d88a00ea0"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.aarch64-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "a467bba7317a93aae3172f8b9c06d2cca0b75d85"
os = "freebsd"

    [[Libffi.download]]
    sha256 = "b589e2a3b8a8d1e6f78678e1225ea0c91f4303ac786040fa6d54450d8e021aa4"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "1b0a9db1fe713cd234bb3ec06906ad5d48742926"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "0e23f45c5604e7a9870e4a4ed4eb88e1005a471596af479546ce69802479df91"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.1+1/Libffi.v3.2.1.x86_64-linux-musl.tar.gz"
