[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "5b90ad21b4b1af3a9446241fb5afe3e3b3eda941"
os = "macos"

    [[Libffi.download]]
    sha256 = "159d7de93f08a05d0e8aa6164c55000a534063de4eb598cc70eecedc32091897"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.aarch64-apple-darwin.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "fc49d723dbdbb9eba916f9604351ab11fe50e687"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "1b62d53ab0141641f69dccef10c50430190336f178d9e8d185244091d3280c3c"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.aarch64-linux-gnu.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "01150d28ecf8e60746393c9d4fa3cba3e6f995fa"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "a72310ba19d79e8f9aa71fa0350f037e883bb240fcd799a4be46df8144e4b61d"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.aarch64-linux-musl.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "76b895f1fff9414b5b81d035550835191abdf48d"
os = "freebsd"

    [[Libffi.download]]
    sha256 = "f9da97751281854f575bda68fc0bc493b50d3f6f378be575829bbd2fe5673b18"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.aarch64-unknown-freebsd.tar.gz"
[[Libffi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c953df97edb04e6693004c01778bcea67ea8e1c7"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "d2c7825829ccec8172079519cccd6065dc1ca8a27a9de56da72aab1a098047ff"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.armv6l-linux-gnueabihf.tar.gz"
[[Libffi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a14d033c917b5469941bdc1f180cbe93a4a09f68"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "58eb23bb734ae088ee977da0c110319fff2895047dd40091d5e0a9c091462a38"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.armv6l-linux-musleabihf.tar.gz"
[[Libffi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32f23c9ae189f9ba6cf216bee20daa66758723f1"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "3745f1294f02b5a478aac7005569fb418895f27a5ce50648ccd1e5c959f58a85"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.armv7l-linux-gnueabihf.tar.gz"
[[Libffi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c3c442149665431258a6faa5a2eb60ee0444209"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "0af23f1d0776185974a66b6ce4c923638ce8f7998522bb095d04be4ac11f41b0"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.armv7l-linux-musleabihf.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "5c056cafe507b14565b09e9d1f9c48422cad626f"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "cfd76b846232f3f97be9cfa71a18a2b63611383bb672f48b18c4ebcc1bd59cfd"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.i686-linux-gnu.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "29a5366f873149bef293caae5019a47784743056"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "2b597178fefe92b7f75858bc0f84f03dc594567a48da3ed20c3e20c8035a0de8"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.i686-linux-musl.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "6691e637f7af4bf0651b4fd261a7a0b12c8debca"
os = "windows"

    [[Libffi.download]]
    sha256 = "2ad6a2971f839d83b05b5c206446051a340b0c652dab8ca44c9a356e7c4e571f"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.i686-w64-mingw32.tar.gz"
[[Libffi]]
arch = "powerpc64le"
git-tree-sha1 = "5e6005c28d6768fc42e02370a2c9c8596b5c95d6"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "2da6c8853965d79dc0efde7bdbf5ccb18f5ecd27b8217b55afcc3c3ef58d6a48"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.powerpc64le-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "605b2aba6b93b6f961cc454658dd7587ca3779e0"
os = "macos"

    [[Libffi.download]]
    sha256 = "3cb0551dafc3867fbd02473a6f15ecba1b8decf79665a22f782631ce952311d3"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.x86_64-apple-darwin.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "08ab7db13fbc32076a77781b2f8bd372cf4c9a8d"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "86853328fabdaaa5dab9e208a4f8022d7f2a05545389ee10a9cda5ae495c746c"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.x86_64-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "6e94190c290892d2a417550fa9e4a12846123c16"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "dca2d843dd071cdce692d80f6857d135353611e681b45f42a63ea258834baa7c"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.x86_64-linux-musl.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "6f62cc31bbe0e54501e30ae0b6a68a08787f5f9c"
os = "freebsd"

    [[Libffi.download]]
    sha256 = "9fca30cd121efbce863d1264c6af66a9149d026bda57563dd7a8582f3aafd212"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.x86_64-unknown-freebsd.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "b0ebd74eb8afa6bfc460434bbc19c05b059cf4fe"
os = "windows"

    [[Libffi.download]]
    sha256 = "4c7834c6e59cb3a7e95366af3fefabc6ddc186e90599c82fe1419149e4b04661"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+2/Libffi.v3.2.2.x86_64-w64-mingw32.tar.gz"
